---
abstract: 'Perl wrapper for ANNOVAR'
author:
  - 'Richard de Borja <richard.deborja@sickkids.ca>'
build_requires:
  File::Temp: '0'
  FindBin: '0'
  MooseX::ClassCompositor: '0'
  Test::Exception: '0'
  Test::Moose: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: NGS-Tools-ANNOVAR
provides:
  NGS::Tools::ANNOVAR:
    file: lib/NGS/Tools/ANNOVAR.pm
    version: '0.08'
  NGS::Tools::ANNOVAR::GeneAnnotation:
    file: lib/NGS/Tools/ANNOVAR/GeneAnnotation.pm
  NGS::Tools::ANNOVAR::TableAnnotation:
    file: lib/NGS/Tools/ANNOVAR/TableAnnotation.pm
  NGS::Tools::ANNOVAR::Utilities:
    file: lib/NGS/Tools/ANNOVAR/Utilities.pm
requires:
  File::Basename: '2.8'
  File::ShareDir: '1.00'
  Moose: '2'
  Moose::Role: '2'
  MooseX::Params::Validate: '0.1'
  autodie: '0'
  namespace::autoclean: '0'
version: '0.08'
