---
abstract: 'Perl wrapper for ANNOVAR'
author:
  - 'Richard de Borja <richard.deborja@sickkids.ca>'
build_requires:
  File::Temp: 0
  FindBin: 0
  MooseX::ClassCompositor: 0
  Test::Exception: 0
  Test::Moose: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NGS-Tools-ANNOVAR
provides:
  NGS::Tools::ANNOVAR:
    file: lib/NGS/Tools/ANNOVAR.pm
    version: 0.07
  NGS::Tools::ANNOVAR::GeneAnnotation:
    file: lib/NGS/Tools/ANNOVAR/GeneAnnotation.pm
    version: 0
  NGS::Tools::ANNOVAR::TableAnnotation:
    file: lib/NGS/Tools/ANNOVAR/TableAnnotation.pm
    version: 0
  NGS::Tools::ANNOVAR::Utilities:
    file: lib/NGS/Tools/ANNOVAR/Utilities.pm
    version: 0
requires:
  File::Basename: 2.8
  Moose: 2
  Moose::Role: 2
  MooseX::Params::Validate: 0.1
  autodie: 0
  namespace::autoclean: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 0.07
